version: '2'
services:
  base:
    image: node:11
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
  install:
    extends:
      service: base
    command: npm i
  build:
    extends:
      service: base
    command: npm run build
  install-bundles:
    extends:
      service: base
    command: npm run install-bundles
